//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StructuredLogging.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StructuredLogging.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structured logging must be used instead of interpolated string.
        /// </summary>
        internal static string Rule0001MessageFormat {
            get {
                return ResourceManager.GetString("Rule0001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolated string is used for logging.
        /// </summary>
        internal static string Rule0001Title {
            get {
                return ResourceManager.GetString("Rule0001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event ID should be passed to the logger.
        /// </summary>
        internal static string Rule0002MessageFormat {
            get {
                return ResourceManager.GetString("Rule0002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass the event ID.
        /// </summary>
        internal static string Rule0002Title {
            get {
                return ResourceManager.GetString("Rule0002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The caught exception should be passed to the logger.
        /// </summary>
        internal static string Rule0003MessageFormat {
            get {
                return ResourceManager.GetString("Rule0003MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass the exception.
        /// </summary>
        internal static string Rule0003Title {
            get {
                return ResourceManager.GetString("Rule0003Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structured logging must be used instead of interpolated string.
        /// </summary>
        internal static string Rule0004MessageFormat {
            get {
                return ResourceManager.GetString("Rule0004MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolated string is used for logging.
        /// </summary>
        internal static string Rule0004Title {
            get {
                return ResourceManager.GetString("Rule0004Title", resourceCulture);
            }
        }
    }
}
